title: Uploaded Fairy
description: "The syndicated version of my webcomic. You can find the link to the main site here: https://lwflouisa.github.io/uploadedfairyalt/"
author:
  name: "LWFlouisa"
  url: "https://lwflouisa.github.io/uploadedfairyalt/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "LWFlouisa"
year : "2020"
